import Cooltitle from "@/Components/Modules/CoolTitle/Cooltitle";
import Head from "next/head";
import React from "react";
import image1 from "../../Assets/about/image1.png";
import image2 from "../../Assets/about/image2.png";
import Image from "next/image";

const About = () => {
  return (
    <div className="px-10 ">
      <Head>
        <title>About - Storyverse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://res.cloudinary.com/dicnezd6a/image/upload/v1682523173/favicon_oleadq.ico"
        />
      </Head>

      <div className="flex justify-center items-center my-2">
        <Cooltitle background="ABOUT" title="ABOUT STORYVERSE" />
      </div>

      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold text-zinc-700">About Us</h1>
          <p className="text-lg my-4 font-semibold text-zinc-600 pr-10">
            Welcome to Storyverse - your one-stop destination for the latest and
            greatest in the world of blogging. Our blog is constantly updated
            with fresh, thought- provoking articles on a variety of topics. From
            current events to personal experiences, our team of talented writers
            cover it all. Whether youre looking for inspiration or just a good
            read, Storyverse has you covered
          </p>
        </div>
        <div>
          <Image className="w-7/12 mx-auto" src={image1} alt="" />
        </div>
      </div>

      <div className="grid my-10 grid-cols-3 gap-10">
        <div>
          <h1 className="text-3xl font-bold text-zinc-700">Contact</h1>
          <p className="text-lg my-4 font-semibold text-zinc-600">
            Address: Lorem 142 Str., 2352, Ipsum,
            <br />
            State: United States of America
            <br />
            Phone: +01-234 56789
            <br />
            If you would like to partner with Ultra at our next event, contact
            us at contact@ultranews.com.
          </p>
        </div>
        <div>
          <h1 className="text-3xl font-bold text-zinc-700">Advertise</h1>
          <p className="text-lg my-4 font-semibold text-zinc-600">
            Please contact us directly at ads@ultranews.com. For large or unique
            campaigns please email sale@ultranews.com for requests-for-proposal
            and additional pricing information.
          </p>
        </div>
        <div>
          <h1 className="text-3xl font-bold text-zinc-700">Event</h1>
          <p className="text-lg my-4 font-semibold text-zinc-600">
            We are a professional event management team, starting in 2012.
            Please send request details to email event@ultranews.com
          </p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-10">
        <div className="">
          <Image src={image2} className="w-7/12 mx-auto" alt="" />
        </div>
        <div className="my-20">
          <h1 className="text-4xl my-4 font-bold text-zinc-700">Get in Touch</h1>
          <div className="flex items-center gap-x-4 w-full">
            <div className="w-full">
              <p className="my-2 font-semibold">Your Name</p>
              <input type="email" name="" className="p-2 w-full" id="" />
            </div>
            <div className="w-full">
              <p className="my-2 font-semibold">Your Email</p>
              <input type="email" name="" className="p-2 w-full" id="" />
            </div>
          </div>
          <div>
            <p className="my-2 font-semibold">Your Name</p>
            <textarea className="w-full h-40" />
          </div>
        </div>
      </div>
    </div>
  );
};

export default About;
