import { LargeBlogCard } from "@/Components/Modules/BlogCard/BlogCard";
import Social from "@/Components/Shared/Social/Social";
import Head from "next/head";
import { AiOutlineSearch } from "react-icons/ai";

const Posts = () => {
  return (
    <div className="px-10 py-4">
      <Head>
        <title>Posts - Story Verse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://res.cloudinary.com/dicnezd6a/image/upload/v1682523173/favicon_oleadq.ico"
        />
      </Head>
      {/* Header */}
      <div className="flex justify-between items-center">
        <nav className="flex lg:my-8 2xl:my-12 gap-x-4 cursor-pointer  items-center">
          <p className="bg-[#003842]  rounded-full hover:bg-[#003842]  text-white hover:text-white px-4 py-1">
            All
          </p>
          <p className="bg-transparent  rounded-full hover:bg-[#003842] text-black hover:text-white px-4 py-1">
            LIFESYTLE
          </p>
          <p className="bg-transparent  rounded-full hover:bg-[#003842] text-black hover:text-white px-4 py-1">
            FASHION
          </p>
          <p className="bg-transparent rounded-full hover:bg-[#003842] text-black hover:text-white px-4 py-1">
            TRAVEL
          </p>
          <p className="bg-transparent  rounded-full hover:bg-[#003842] text-black hover:text-white px-4 py-1">
            SPORTS
          </p>
        </nav>

        <div className="relative">
          <AiOutlineSearch className="absolute text-xl top-3 left-2" />
          <input
            type="text"
            className="bg-[#D9D9D9] p-2 w-[400px] px-8 focus:outline-none text-zinc-600 rounded-full "
          />
        </div>
          </div>
          
          {/* Body */}
          <div className="grid my-4 gap-x-10 grid-cols-4">
              <div className="col-span-3 grid grid-cols-2 gap-10">
                  <LargeBlogCard/>
                  <LargeBlogCard/>
                  <LargeBlogCard/>
                  <LargeBlogCard/>
              </div>
              <div className="col-span-1">
                  <Social title="text-zinc-700"/>
              </div>
              <p className="my-4 text-font-semibold bg-[#EF3F48] px-4 py-1 rounded-full text-white  cursor-pointer w-fit">View More</p>
          </div>
    </div>
  );
};

export default Posts;
